spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/crm_db
    username: postgres     # Aligned with docker-compose
    password: postgres     # Aligned with docker-compose
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: redis          # Use service name 'redis', not 'localhost'
      port: 6379

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
app:
  super-admin:
    email: admin@crm.com
    password: SuperAdmin123!
    first-name: Super
    last-name: Admin
  flyway:
    clean-on-startup: ${FLYWAY_CLEAN_ON_STARTUP:false}

logging:
  level:
    root: DEBUG
    org.pfa.authservice: TRACE    # Aligned with org.pfa package structure
    org.flywaydb: TRACE
    org.springframework.security: DEBUG