server:
  port: 8083

spring:
  application:
    name: billing-service
  config:
    import: "optional:configserver:http://config-server:8888" # localhost -> config-server
  datasource:
    url: jdbc:postgresql://postgres-db:5432/crm_db
    username: postgres
    password: postgres     # password -> postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # update -> validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  # Added Kafka Config
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/ # localhost -> eureka-server

jwt:
  secret: ${JWT_SECRET_KEY}