server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://config-server:8888" # Added Config Server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service-public
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/login, /api/auth/register, /api/auth/refresh
          filters:
            - RemoveRequestHeader=Cookie
        - id: auth-service-protected
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter
        - id: sales-service
          uri: lb://sales-service
          predicates:
            - Path=/api/sales/**
          filters:
            - AuthenticationFilter
        - id: billing-service-admin
          uri: lb://billing-service
          predicates:
            - Path=/api/billing/admin/**
          filters:
            - name: AuthenticationFilter
              args:
                isAdminOnly: true
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/billing/**
          filters:
            - AuthenticationFilter

# Added Eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: ${JWT_SECRET_KEY} # Replaced hardcoded key

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.pfa.gatewayservice: DEBUG