server:
  port: 8080

spring:
  cloud:
    gateway:
      # 1. Discovery Client (Locates services via Eureka)
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # 2. CORS Configuration (Fixes "Cross-Origin" errors with Angular)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200" # Your local Angular app
              - "http://localhost"      # Production Frontend (if served via Nginx)
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      # 3. Routes (Traffic Cop)
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: sales-service
          uri: lb://sales-service
          predicates:
            - Path=/api/sales/**

        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/billing/**

# 4. Security (Used if Gateway does token parsing)
jwt:
  secret: ${JWT_SECRET_KEY}