server:
  port: 8080

spring:
  application:
    name: gateway-service
  server:
    port: 8080


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: sales-service
          uri: lb://sales-service
          predicates:
            - Path=/api/sales/**
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/billing/**

  jwt:
    secret: ${JWT_SECRET_KEY}