server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4201" # Admin Panel
              - "http://localhost:4200" # Public Client
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        # --- PUBLIC ROUTES (No Auth Required) ---
        
        # User Service (Login/Register)
        - id: auth-service-public
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/v1/users/**
          filters:
            - RewritePath=/user-service/?(?<remaining>.*), /${remaining}

        # # Public Content (Viewing services)
        # - id: content-service-public
        #   uri: lb://CONTENT-SERVICE
        #   predicates:
        #     - Path=/content-service/api/v1/content/pages/**
        #     - Method=GET
        #   filters:
        #     - RewritePath=/content-service/?(?<remaining>.*), /${remaining}

        # # Public Jobs (Requesting a quote)
        # - id: job-service-public
        #   uri: lb://JOB-SERVICE
        #   predicates:
        #     - Path=/job-service/api/v1/quotes
        #     - Method=POST
        #   filters:
        #     - RewritePath=/job-service/?(?<remaining>.*), /${remaining}

        # # Customer Service (Public Search/Create)
        # - id: customer-service-public
        #   uri: lb://CUSTOMER-SERVICE
        #   predicates:
        #     - Path=/customer-service/api/v1/customers/**
        #   filters:
        #     - RewritePath=/customer-service/?(?<remaining>.*), /${remaining}


        # # --- SECURED ROUTES (Auth Required) ---
        
        # # Admin: Manage Content (Create/Update Pages)
        # - id: content-service-admin
        #   uri: lb://CONTENT-SERVICE
        #   predicates:
        #     - Path=/content-service/api/v1/content/**
        #   filters:
        #     - RewritePath=/content-service/?(?<remaining>.*), /${remaining}
        #     - name: AuthenticationFilter # <--- ENFORCES JWT CHECK
        #       args:
        #         isAdminOnly: true

        # # Admin: Manage Quotes & Jobs (View/Update)
        # - id: job-service-admin
        #   uri: lb://JOB-SERVICE
        #   predicates:
        #     - Path=/job-service/api/v1/quotes/**
        #     # Allow GET/PUT/DELETE only for admins. POST (Create) is public.
        #     - Method=GET,PUT,DELETE 
        #   filters:
        #     - RewritePath=/job-service/?(?<remaining>.*), /${remaining}
        #     - name: AuthenticationFilter
        #       args:
        #         isAdminOnly: true

        # # Admin: Manage Users
        # - id: user-service-admin
        #   uri: lb://USER-SERVICE
        #   predicates:
        #     - Path=/user-service/api/v1/admin/**
        #   filters:
        #     - RewritePath=/user-service/?(?<remaining>.*), /${remaining}
        #     - name: AuthenticationFilter
        #       args:
        #         isAdminOnly: true

        # # Admin: Invoice Service
        # - id: invoice-service-admin
        #   uri: lb://INVOICE-SERVICE
        #   predicates:
        #     - Path=/invoice-service/api/v1/invoices/**
        #   filters:
        #     - RewritePath=/invoice-service/?(?<remaining>.*), /${remaining}
        #     - name: AuthenticationFilter
        #       args:
        #         isAdminOnly: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
application:
  security:
    jwt:
      # MUST MATCH THE KEY IN USER-SERVICE EXACTLY
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000